export const GET_ACTIVITIES_REQUEST = 'GET_ACTIVITIES_REQUEST'
export const GET_ACTIVITIES_SUCCESS = 'GET_ACTIVITIES_SUCCESS'
export const GET_ACTIVITIES_FAIL = 'GET_ACTIVITIES_FAIL'

export const GET_ACTIVITY_REQUEST = 'GET_ACTIVITY_REQUEST'
export const GET_ACTIVITY_SUCCESS = 'GET_ACTIVITY_SUCCESS'
export const GET_ACTIVITY_FAIL = 'GET_ACTIVITY_FAIL'

export const ADD_ACTIVITY_REQUEST = 'ADD_ACTIVITY_REQUEST'
export const ADD_ACTIVITY_SUCCESS = 'ADD_ACTIVITY_SUCCESS'
export const ADD_ACTIVITY_FAIL = 'ADD_ACTIVITY_FAIL'

export const DELETE_ACTIVITY_REQUEST = 'DELETE_ACTIVITY_REQUEST'
export const DELETE_ACTIVITY_SUCCESS = 'DELETE_ACTIVITY_SUCCESS'
export const DELETE_ACTIVITY_FAIL = 'DELETE_ACTIVITY_FAIL'

export const EDIT_ACTIVITY_REQUEST = 'EDIT_ACTIVITY_REQUEST'
export const EDIT_ACTIVITY_SUCCESS = 'EDIT_ACTIVITY_SUCCESS'
export const EDIT_ACTIVITY_FAIL = 'EDIT_ACTIVITY_FAIL'

